//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebbsidaExam
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckaInBil
    {
        public int Id { get; set; }
        public string RegNr { get; set; }
        public string Marke { get; set; }
        public string Modell { get; set; }
        public string Vaxellada { get; set; }
        public string Miltal { get; set; }
        public string Kostnad { get; set; }
    }
}
